### PR TITLE
docs: initial content for Extending Classes and Implementing Interfac…

### PR DESCRIPTION
**Pull request by Ombuweb**
…es Android

### CODE REVIEW

**Comment by vallemar** [comment]
Why do this https://github.com/NativeScript/docs/pull/28/files#diff-70925e72212c56f9d0c078f75198908a4309d0f96c256a086bfdb8d9f9e16b20R525 instead of just doing this? `new ClickListenerImpl()`, and by the same token, why is this `initializeClickListener()` necessary?

If it is necessary to do this I think it would be worth mentioning

**Comment by rigor789** [comment]
I believe we can refactor that to not use the initialize function. The main reason that was documented that way in the old docs was because of snapshots, they needed all native code to be deferred/not ran during snapshots only during runtime, so many parts of core still follow that pattern, but it is no longer necessary or recommended, since snapshot support has been deprecated/dropped in NS7.

**Comment by vallemar** [comment]
@rigor789 Perfect, I said it because it seems like a black magic that was not explained. If it is no longer needed much better since it is finally less to understand for the developer, create your class, instantiate it and working

**Comment by NathanWalker** [comment]
Thanks or mention @vallemar I switched docs examples to not use the function closures since snapshots are not used.

**Pull request merged**
