### PR TITLE
docs: ImageSource

### PR DESCRIPTION
**Pull request by Ombuweb**

### CODE REVIEW

**Comment by Ombuweb** [comment]
I need help with examples for `ImageSource.fromData()`  and `ImageSource.fromFontIconCodeSync()`. I tried

`const img = ImageSource.fromFontIconCodeSync("&#xf044;", new Font("serif", 12),new Color("red")) ` but it's not converting that string to an icon.

**Comment by Ombuweb** [comment]
When is it ideal to use `fromAsset()` ?  It seems to achieve the same result as `fromFile()` but the latter being simpler.

**Comment by rigor789** [comment]
> When is it ideal to use `fromAsset()` ? It seems to achieve the same result as `fromFile()` but the latter being simpler.

Sometimes you have an ImageAsset instance you need to convert, for example when taking an image with the camera usually results in an ImageAsset, which you convert to ImageSource to display in the app. There are likely other cases where that's useful, but I can't think of any.

**Comment by Ombuweb** [comment]
I think the [ImageAsset](https://github.com/NativeScript/NativeScript/blob/main/packages/core/image-asset/index.d.ts) class has bugs.  On iOS, the `ios`  property returns `undefined`  and the `nativeImage`  property returns` undefined` on Android.

**Comment by Ombuweb** [comment]
@rigor789 I think we should move `ImageSource` from `/guide/core` to `/guide/ui/image-source`. Then for the sidebar we can have following structure:

**UI**
...
- Image
    - **index.md** (component content)
    - **image-source.md**
    - **image-cache.md**

...

**Comment by rigor789** [comment]
`/guide/ui/image-source` sounds good 👍

**Pull request merged**
